### ISSUE TITLE
Empty finish project

### ISSUE THREAD

**Issue by Monserg** [appcoda/QuickLookDemo#2]
Hi,
in 15.04.16 I read your article about Quick Look Framework & do all code.
After finish I want to compare my code with your finished code.
I download it but it will be empty.
Decide - fix it or not :-).
Best regards,
Sergey M.

**Comment by suricforever** [comment]
I have push a [PR](https://github.com/zhangxiaolian1991/QuickLookDemo) which contain final project to the demo
