### ISSUE TITLE
Unsupported Swift version

### ISSUE THREAD

**Issue by richardtop** [appcoda/QuickLookDemo#6]
Please, convert the project to the latest Swift version (4.1).
![image](https://user-images.githubusercontent.com/8013017/40614769-d5a1869c-628c-11e8-86a4-5b8e39e30344.png)

**Comment by carloshmartins** [comment]
Hello, Richard. I've fixed the problem and migrated to Swift 4.1 already. Can i create a pull request with the solution? Thanks.

**Comment by richardtop** [comment]
Hi @carloshmartins, I'm not the maintainer of this repository, and apparently, the demo is empty. I went  with a different project to see the QuickLook in practice.

NB: Apple sample code is outdated too.

You of course can create a pull request, but I'm not sure if it gets merged.

**Comment by rajahimanath** [comment]
Can we rely on this? Is this going to be maintained in future?
